name: Release

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get release version from tag
      id: release_tag
      env:
        GITHUB_REF: ${{ github.ref }}
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache maven dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Maven release
      run: |
        mvn --batch-mode versions:set -DnewVersion=${{ steps.release_tag.outputs.tag }} -DprocessAllModules -DgenerateBackupPoms=false
        mvn clean deploy
        mvn --batch-mode build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}-SNAPSHOT -DprocessAllModules -DgenerateBackupPoms=false
    - name: Commit and push files
      run: |
        git switch -c master
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "New SNAPSHOT version" -a
        git push origin master
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
